# Generated by Django 4.2.4 on 2023-08-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cliente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ManyToManyField(to='core.endereco'),
        ),
    ]
